#define TALLOC_VERSION_MAJOR 2
#define TALLOC_VERSION_MINOR 4
#define TALLOC_BUILD_VERSION_MAJOR 2
#define TALLOC_BUILD_VERSION_MINOR 4
#define TALLOC_BUILD_VERSION_RELEASE 3

#define HAVE_GETAUXVAL 1
#define HAVE_SYS_AUXV_H 1
#define HAVE_STDBOOL_H 1
#define HAVE_BOOL 1
#define HAVE_MEMSET_S 1
#define HAVE_VA_COPY 1
#define HAVE___THREAD 1
#define HAVE_FUNCTION_MACRO 1
#define HAVE_VOLATILE 1
#define HAVE_GCC_VOLATILE_MEMORY_PROTECTION 1
