name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Lix
        uses: canidae-solutions/lix-quick-install-action@v4

      - name: Lint
        run: nix develop .#default --command just lint

      - name: Build all test problems
        run: nix develop .#default --command just all-problems
